version: "3.8"

services:
  db:
    image: postgres:15
    container_name: chat-db
    restart: always
    environment:
      POSTGRES_USER: chat_user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: chat_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    volumes:
      - ./app:/app/app   # синхронизируем локальную папку с контейнером
      - ./uploads:/app/uploads
    dns:
      - 8.8.8.8
      - 1.1.1.1
    container_name: chat-backend
    restart: always
    depends_on:
      - db
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    container_name: chat-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./uploads:/app/uploads:ro # ro = read-only, Nginx только читает
    depends_on:
      - backend

volumes:
  postgres_data:
