// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB478Fnt0PGG8blZEnGC3OEX1JQdeI6UF0',
    appId: '1:508330035457:web:80bda4cfc3d86291103300',
    messagingSenderId: '508330035457',
    projectId: 'langbridge-17ead',
    authDomain: 'langbridge-17ead.firebaseapp.com',
    storageBucket: 'langbridge-17ead.firebasestorage.app',
    measurementId: 'G-CHDB93XD0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj0coAvdjSb4Zi-8y38CpcdQRLcgWE9TY',
    appId: '1:508330035457:android:353133afb51f5891103300',
    messagingSenderId: '508330035457',
    projectId: 'langbridge-17ead',
    storageBucket: 'langbridge-17ead.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzhjXtOEkepeefQ12g3ivpsYtR9VEg6lo',
    appId: '1:508330035457:ios:240a41842323adf0103300',
    messagingSenderId: '508330035457',
    projectId: 'langbridge-17ead',
    storageBucket: 'langbridge-17ead.firebasestorage.app',
    iosBundleId: 'com.example.langbridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzhjXtOEkepeefQ12g3ivpsYtR9VEg6lo',
    appId: '1:508330035457:ios:240a41842323adf0103300',
    messagingSenderId: '508330035457',
    projectId: 'langbridge-17ead',
    storageBucket: 'langbridge-17ead.firebasestorage.app',
    iosBundleId: 'com.example.langbridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB478Fnt0PGG8blZEnGC3OEX1JQdeI6UF0',
    appId: '1:508330035457:web:334ff658b15fa61d103300',
    messagingSenderId: '508330035457',
    projectId: 'langbridge-17ead',
    authDomain: 'langbridge-17ead.firebaseapp.com',
    storageBucket: 'langbridge-17ead.firebasestorage.app',
    measurementId: 'G-T40CV3Y8WF',
  );

}